name: Pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run
      run: python hello.py
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: .



